
server:
  port: 8761

spring:
  application:
    name: douding-eureka

eureka:
  instance:
    hostname: domain-eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://domain-eureka:8761/eureka/





